name: Upload to AWS S3

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: echo "npm run build"  
     
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:

    # - name: Set up AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: 
    #     aws-secret-access-key: 
    #     aws-region: 

    - name: Copy file to S3
      run: echo aws s3 cp ./path/to/your/file.txt s3://your-bucket-name/path/in/bucket/
